services:
    web:
        image: alangiacomin/k8s-app:latest
        build:
            target: web
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "80:8123"
        volumes:
            - .:/var/www/html
    queue:
        image: alangiacomin/k8s-app-queue:latest
        build:
            context: .
            dockerfile: Dockerfile.queue
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        depends_on:
            web:
                condition: service_started
                required: true
